### ISSUE TITLE
panic: websocket: close 1006 (abnormal closure): unexpected EOF

### ISSUE THREAD

**Issue by npafitis** [watson-developer-cloud/go-sdk#39]
**Overview**
I basically use a similar go application to that of the [example](https://github.com/watson-developer-cloud/go-sdk/blob/master/examples/speechtotextv1/speech_to_text_v1.go) for Speech to Text that can be found in this repository, only changes i've made were the service url, my IAM api key and the file that i want to get the text of. I basically copy-pasted the websocket example, but i'm getting 
```
panic: websocket: close 1006 (abnormal closure): unexpected EOF
```
although my mp3 file doesn't seem to be corrupted.

**Expected behavior**
Print out the converted speech of the audio file in to text.

**Actual behavior**
This is the full output after running.
```
panic: websocket: close 1006 (abnormal closure): unexpected EOF

goroutine 14 [running]:
main.myCallBack.OnError(...)
	/home/nikolas/go/src/ibmWatson/main.go:67
github.com/watson-developer-cloud/go-sdk/speechtotextv1.RecognizeListener.OnError(...)
	/home/nikolas/go/src/github.com/watson-developer-cloud/go-sdk/speechtotextv1/websocket_listener.go:70
github.com/watson-developer-cloud/go-sdk/speechtotextv1.RecognizeListener.OnData(0xc0004d20e0, 0x7c6580, 0x9f63e0, 0xc0000c8000, 0xc0000891e0)
	/home/nikolas/go/src/github.com/watson-developer-cloud/go-sdk/speechtotextv1/websocket_listener.go:44 +0x1ed
created by github.com/watson-developer-cloud/go-sdk/speechtotextv1.(*SpeechToTextV1).NewRecognizeListener
	/home/nikolas/go/src/github.com/watson-developer-cloud/go-sdk/speechtotextv1/websocket_listener.go:128 +0x295

Process finished with exit code 2
```

**How to reproduce**
This is the actual code:
```go
package main

import (
	"encoding/json"
	"fmt"
	"github.com/IBM/go-sdk-core/core"
	"github.com/watson-developer-cloud/go-sdk/speechtotextv1"
	"os"
)

func main() {
	// Instantiate the Watson Speech To Text service
	service, serviceErr := speechtotextv1.
		NewSpeechToTextV1(&speechtotextv1.SpeechToTextV1Options{
			URL:       "https://gateway-lon.watsonplatform.net/speech-to-text/api",
			IAMApiKey: "<My-Key>",
		})

	// Check successful instantiation
	if serviceErr != nil {
		panic(serviceErr)
	}

	/* RECOGNIZE */

	pwd, _ := os.Getwd()

	// Open file with mp3 to recognize
	audio, audioErr := os.Open(pwd + "/2019_02_27_18_46_40.mp3")
	if audioErr != nil {
		panic(audioErr)
	}

	// callbook can have `OnOpen`, `onData`, `OnClose` and `onError` functions
	callback := myCallBack{}

	recognizeUsingWebsocketOptions := service.
		NewRecognizeUsingWebsocketOptions(audio, "audio/mp3")

	recognizeUsingWebsocketOptions.
		SetModel("en-US_BroadbandModel").
		SetWordConfidence(true).
		SetSpeakerLabels(true).
		SetTimestamps(true)

	service.RecognizeUsingWebsocket(recognizeUsingWebsocketOptions, callback)
}

type myCallBack struct{}

func (cb myCallBack) OnOpen() {
	fmt.Println("Handshake successful")
}

func (cb myCallBack) OnClose() {
	fmt.Println("Closing connection")
}

func (cb myCallBack) OnData(resp *core.DetailedResponse) {
	var speechResults speechtotextv1.SpeechRecognitionResults
	result := resp.GetResult().([]byte)
	json.Unmarshal(result, &speechResults)
	core.PrettyPrint(speechResults, "Recognized audio: ")
}

func (cb myCallBack) OnError(err error) {
	panic(err)
}
```

**SDK Version**
v0.8.0

**Additional information:**
- OS: Ubuntu 16.04
- go version go1.12.3 linux/amd64

**Additional context**
Information about the mp3 file.
```bash
$ stat 2019_02_27_18_46_40.mp3 
  File: '2019_02_27_18_46_40.mp3'
  Size: 56586239
  Blocks: 110520
  IO Block: 4096   regular file
Device: 804h/2052d	Inode: 7602323     Links: 1
```

```bash
$ ffprobe 2019_02_27_18_46_40.mp3 
ffprobe version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2007-2018 the FFmpeg developers

[mp3 @ 0x182ad00] Skipping 0 bytes of junk at 0.
[mp3 @ 0x182ad00] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from '2019_02_27_18_46_40.mp3':
  Duration: 00:58:56.64, start: 0.000000, bitrate: 127 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, mono, s16p, 128 kb/s
```

**Comment by theThinkingCap** [comment]
Hi @npafitis, I ran your code in my local, and it works for the Tokyo and America service locations. Does your application produce any speech recognition results before aborting?

**Comment by ehdsouza** [comment]
@npafitis , seems like a similar issue was seen using the underlying gorilla library. Possible solutions that users found were:
* Increase the `HandshakeTimeout`
* Make sure you are not behind a firewall

Let me know if these work for you.

**Comment by ehdsouza** [comment]
@npafitis is this still an issue?

**Comment by n-pafitis** [comment]
@ehdsouza I abandoned the project, but later today i will reproduce the problem and see whether it is still an issue.
